# This workflow will build and deploy strands on changes to main

name: GoBuild

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  TAG_NAME: v${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Dependencies
      run: |
        sudo apt install xorg-dev libgl1-mesa-dev libopenal1 libopenal-dev libvorbis0a libvorbis-dev libvorbisfile3
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go mod tidy
        
    - name: Build Strands
      run: go build . 
      
    - name: Run vet & lint
      run: |
        go vet .
        staticcheck .
  
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/strands
          asset_name: strands-${{ env.TAG_NAME }}-${{ matrix.os }}-${{ matrix.arch }}.bin
          asset_content_type: application/octet-stream
        