# This workflow will attempt to build strands on changes to main

name: GoBuild

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Dependencies
      run: |
        sudo apt install xorg-dev libgl1-mesa-dev libopenal1 libopenal-dev libvorbis0a libvorbis-dev libvorbisfile3
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go mod tidy
        
    - name: Lint & Vet
      run: |
       go vet .
       staticcheck .
        
    - name: Build Strands
      run: go build . 
  