# This workflow will build and deploy strands on changes to main

name: GoBuild

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'
    
    - name: Install Dependencies
      run: |
        apt-get install xorg-dev libgl1-mesa-dev libopenal1 libopenal-dev libvorbis0a libvorbis-dev libvorbisfile3
        go mod tidy
        
    - name: Build Strands
      run: go build . 
      
    # Run vet & lint on the code
    # - name: Run vet & lint
    #   run: |
    #     go vet .
    #     golint .
    
    # Run testing on the code
    # - name: Run testing
    #   run: cd test && go test -v

  deploy:
    runs-on: ubuntu-latest
    needs: [build]  # Only run this workflow when "build" workflow succeeds
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}  # Only run this workflow if it is main branch on push event
    steps:
    - uses: actions/checkout@v3

    