# This workflow will build Strands
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GoBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: go/src/github.com/cbeimers113/strands

    - name: Build
      run: go build -v ./...
      env:
        GOPATH: /home/runner/work/cbeimers113/go
